import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import Script from 'next/script'
import mongoose from 'mongoose'
import Product from '../models/Product'

export default function Home() {
  return (
    <div className='min-h-screen'>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <a rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
            
      </main>

      
    </div>
  )
}
