import Head from 'next/head' 
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Admissions() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Admissions</title>
        <meta name="description" content="Generated by create next app" />
        <a rel="icon" href="/favicon.ico" />
        {/* <script src= "hey.js"></script> */}
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          This will be your Admissions Page.
        </h1>
        <div className={styles.grid}>

        </div>
      </main>
      <footer className={styles.footer}>
        <a href="/about" rel="noopener noreferrer">
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}