import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
// import { Html, Main, Head, NextScript } from 'next/document'


// var data1 = `<p>${data.information[0].content}</p>`
// console.log(data1);
export default function Blog(props) {
  console.table(props.data.information)
  return (
    <div className={styles.container}>
      <Head>
        <title>My first Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <a rel="icon" href="/favicon.ico" />
        {/* <script src= "hey.js"></script> */}
        {/*  */}
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Blogs about different companies.
        </h1>

        <p className={styles.description}>
          My Blogs
          <code className={styles.code}>#firsttime</code>
        </p>
        <div className={styles.grid}>

          <div className={styles.card}>
            <h2 className={styles.card}>{props.data.information[0].title} &rarr;</h2>
            <p>{props.data.information[0].content}</p>
          </div>

          <div className={styles.card}>
            <h2 className={styles.card}>{props.data.information[1].title} &rarr;</h2>
            <p>{props.data.information[1].content}</p>
          </div>

          <div className={styles.card}>
            <h2 className={styles.card}>{props.data.information[2].title} &rarr;</h2>
            <p>{props.data.information[2].content}</p>
          </div>

          <div className={styles.card}>
            <h2 className={styles.card}>{props.data.information[3].title} &rarr;</h2>
            <p>
            {props.data.information[3].content}
            </p>
          </div>
        </div>
        <script type="script/javascript">
        </script>
      </main>

      <footer className={styles.footer}>
        <a href="/about" rel="noopener noreferrer">
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps(context) {
  let fetcher = await fetch(`${process.env.NEXT_PUBLIC_HOST}/api/hello`);
  let data = await fetcher.json()
  return {
    props: {data}, // will be passed to the page component as props
  }
}
