import Head from 'next/head' 
import Link from 'next/link'
import Image from 'next/image'

export default function Contact() {
  return (
    <div className="">
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <a rel="icon" href="/favicon.ico" />
        {/* <script src= "hey.js"></script> */}
      </Head>

      <main className="">
        <h1 className="">
        This will be your Contact Page.
          </h1>
        <div className="">

        </div>
      </main>
      <footer className="">
        <h1 className="">
          Footer
        </h1>
      </footer>
    </div>
  )
}