import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import Script from 'next/script'
import mongoose from 'mongoose'
import Product from '../models/Product'

export default function Home({ products }) {
  return (
    <div className="">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <a rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <section className="text-gray-600 body-font">
          <div className="container px-5 py-24 mx-auto">

            <div className="flex flex-wrap -m-4">

              {Object.keys(products).map((item) => {
                return <Link href={`/products/${products[item].slug}`}><div key={item._id} className="lg:w-1/4 md:w-1/2 p-4 w-full h-32">
                  <a className="block relative h-48 rounded overflow-hidden">
                    <img alt="ecommerce" className="object-cover object-center w-full h-full block" src={products[item].img}></img>
                  </a>
                  <div className="mt-4">
                    <h3 className="text-gray-500 text-xs tracking-widest title-font mb-1">{products[item].title}</h3>
                    <h2 className="text-gray-900 title-font text-lg font-medium">{products[item].category}</h2>
                    <p className="mt-1">₹{products[item].price}</p>
                  </div>
                  </div>
                </Link>
              })}

            </div>

          </div>
        </section>
      </main>

      <footer className="fixed-bottom">
        {/* <iframe src={"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3457.665446781924!2d78.14812771516841!3d29.931532230852543!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3909465a2fbd565d%3A0x29460ebf9700e9e5!2sSwami%20Hariharanand%20Public%20School!5e0!3m2!1sen!2sin!4v1664115415940!5m2!1sen!2sin"} width={"600"} height={"450"} loading={"lazy"} referrerpolicy={"no-referrer-when-downgrade"}></iframe> */}
      </footer>
    </div>
  )
}

export async function getServerSideProps(context) {
  if (!mongoose.connections[0].readyState) {
    await mongoose.connect(process.env.MONGO_URI)
  }
  let products = await Product.find()

  return {
    props: { products: JSON.parse(JSON.stringify(products)) }, // will be passed to the page component as props
  }
}
