import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import Script from 'next/script'

export default function Home({cart}) {
  return (
    <div className="">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <a rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <section class="text-gray-600 body-font">
          <div class="container px-5 py-24 mx-auto">

            <div class="flex flex-wrap -m-4">

              {Object.keys(cart).map((k)=>{<div key ={k} class="lg:w-1/4 md:w-1/2 p-4 w-full">
                <a class="block relative h-48 rounded overflow-hidden">
                  <img alt="ecommerce" class="object-cover object-center w-full h-full block" src="https://dummyimage.com/420x260"></img>
                </a>
                <div class="mt-4">
                  <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">CATEGORY</h3>
                  <h2 class="text-gray-900 title-font text-lg font-medium">{cart[k].name}</h2>
                  <p class="mt-1">$16.00</p>
                </div>
              </div>})}

            </div>

          </div>
        </section>
      </main>

      <footer className="">
        <a href="/about" rel="noopener noreferrer">
          Powered by{' '}
          <span className="">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        <iframe src={"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3457.665446781924!2d78.14812771516841!3d29.931532230852543!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3909465a2fbd565d%3A0x29460ebf9700e9e5!2sSwami%20Hariharanand%20Public%20School!5e0!3m2!1sen!2sin!4v1664115415940!5m2!1sen!2sin"} width={"600"} height={"450"} loading={"lazy"} referrerpolicy={"no-referrer-when-downgrade"}></iframe>
      </footer>
    </div>
  )
}
