import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/About.module.css'
import Script from 'next/script'
// import { Html, Main, Head, NextScript } from 'next/document'

export default function Spage() {

    return (
        <div>
            <head>
                <title>My first Blogs</title>
                <meta name="description" content="Generated by create next app" />
                <a rel="icon" href="/favicon.ico" />
            </head>
            <main>
                <br />
                <center>
                    <div className='mt-64'>
                        <h2>Anant Jain</h2>
                        <h2>VI Atri</h2>
                        <h2>SHPS</h2>
                    </div>
                </center>
            </main>
        </div>
    )
}
