import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/About.module.css'
import Script from 'next/script'
import { Html, Main, Head, NextScript } from 'next/document'

export default function Spage() {

    return (
        <Html>
            <Head>
                <title>My first Blogs</title>
                <meta name="description" content="Generated by create next app" />
                <a rel="icon" href="/favicon.ico" />
                <Script src="/hey.js"></Script>
                <NextScript></NextScript>
            </Head>
            <Main>
                <br />
                <center>
                    <div className={styles.inp}>
                        <h2>Anant Jain</h2>
                        <h2>VI Atri</h2>
                        <h2>SHPS</h2>
                    </div>
                </center>
            </Main>
        </Html>
    )
}
