import Head from 'next/head'
import * as fkr from '@faker-js/faker'
import Script from 'next/script'

export default function Translate() {

    return (

        <div>
            <Head>
                <title>My first Blogs</title>
                <meta name="description" content="Generated by create next app" />
                <a rel="icon" href="/favicon.ico" />
                <Script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit">
                </Script>
                <Script type="text/javascript">
                    {/* function googleTranslateElementInit() {
            new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element')
            } */}
                </Script>
            </Head>
            <main>
                <div id="google_translate_element"></div>
                <br />
            </main>
        </div>
    )
}
